[0.256s] Invoking command in '/workspaces/isaac_ros-dev/build/velodyne_msgs': /usr/bin/cmake --build /workspaces/isaac_ros-dev/build/velodyne_msgs -- -j12 -l12
[1.154s] Traceback (most recent call last):
[1.154s]   File "/usr/lib/python3.8/genericpath.py", line 19, in exists
[1.154s]     os.stat(path)
[1.154s] FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/pyFirmata-1.1.0.dist-info/namespace_packages.txt'
[1.154s] 
[1.155s] During handling of the above exception, another exception occurred:
[1.155s] 
[1.155s] Traceback (most recent call last):
[1.155s]   File "setup.py", line 1, in <module>
[1.155s]     from setuptools import find_packages
[1.155s]   File "/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py", line 16, in <module>
[1.155s]     import setuptools.version
[1.155s]   File "/usr/local/lib/python3.8/dist-packages/setuptools/version.py", line 1, in <module>
[1.155s]     import pkg_resources
[1.156s]   File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 3260, in <module>
[1.156s]     def _initialize_master_working_set():
[1.156s]   File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 3234, in _call_aside
[1.156s]     f(*args, **kwargs)
[1.156s]   File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 3285, in _initialize_master_working_set
[1.156s]     tuple(
[1.156s]   File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 3286, in <genexpr>
[1.156s]     dist.activate(replace=False)
[1.157s]   File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 2802, in activate
[1.157s]     for pkg in self._get_metadata('namespace_packages.txt'):
[1.157s]   File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 2785, in _get_metadata
[1.157s]     if self.has_metadata(name):
[1.157s]   File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 1425, in has_metadata
[1.157s]     return self._has(path)
[1.157s]   File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 1623, in _has
[1.157s]     return os.path.exists(path)
[1.157s]   File "/usr/lib/python3.8/genericpath.py", line 19, in exists
[1.158s]     os.stat(path)
[1.158s] KeyboardInterrupt
[1.158s] [  2%] Built target velodyne_msgs__cpp
[1.158s] [ 12%] Built target velodyne_msgs__rosidl_generator_c
[1.158s] [ 12%] Built target ament_cmake_python_copy_velodyne_msgs
[1.158s] [ 23%] Built target velodyne_msgs__rosidl_typesupport_cpp
[1.158s] [ 33%] Built target velodyne_msgs__rosidl_typesupport_fastrtps_cpp
[1.159s] [ 43%] Built target velodyne_msgs__rosidl_typesupport_fastrtps_c
[1.159s] [ 53%] Built target velodyne_msgs__rosidl_typesupport_introspection_cpp
[1.159s] [ 64%] Built target velodyne_msgs__rosidl_typesupport_introspection_c
[1.159s] [ 74%] Built target velodyne_msgs__rosidl_typesupport_c
[1.159s] [ 74%] Built target velodyne_msgs
[1.159s] [ 76%] Built target velodyne_msgs__py
[1.159s] [ 84%] Built target velodyne_msgs__rosidl_generator_py
[1.159s] [ 89%] Built target velodyne_msgs__rosidl_typesupport_c__pyext
[1.160s] [ 94%] Built target velodyne_msgs__rosidl_typesupport_introspection_c__pyext
[1.160s] [100%] Built target velodyne_msgs__rosidl_typesupport_fastrtps_c__pyext
[1.169s] make[2]: *** [CMakeFiles/ament_cmake_python_build_velodyne_msgs_egg.dir/build.make:70: CMakeFiles/ament_cmake_python_build_velodyne_msgs_egg] Interrupt
[1.170s] make[1]: *** [CMakeFiles/Makefile2:447: CMakeFiles/ament_cmake_python_build_velodyne_msgs_egg.dir/all] Interrupt
[1.170s] make: *** [Makefile:146: all] Interrupt
